name: CodeSample

options:
  preGenCommand: swiftgen
  generateEmptyDirectories: true
  createIntermediateGroups: true

projectReferences:
  Core:
    path: Modules/Core/Core.xcodeproj
    embed: true
  
  Components:
    path: Modules/Components/Components.xcodeproj
    embed: true
  

targets:
  CodeSample:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: CodeSample

    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        PRODUCT_BUNDLE_IDENTIFIER: "com.adauto.CodeSample"
        DEVELOPMENT_TEAM: C2BTWK9QR9
        TARGETED_DEVICE_FAMILY: 1
        MARKETING_VERSION: "1.1.2"
        CURRENT_PROJECT_VERSION: "1"

      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic

        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.adauto.CodeSample"

    dependencies:
      - framework: Carthage/Build/RxSwift.xcframework
      - framework: Carthage/Build/RxCocoa.xcframework
      - framework: Carthage/Build/RxRelay.xcframework
      - framework: Carthage/Build/TinyConstraints.xcframework
      - framework: Carthage/Build/AloeStackView.xcframework
      - target: Core/Core
      - target: Components/Components

    preBuildScripts:
      - script: swiftgen
        name: Swiftgen
      
      - script: swiftlint
        name: Swiftlint
  
  CodeSampleTests:
    type: bundle.unit-test
    platform: iOS
    sources: CodeSampleTests
    schemes:
      testTargets:
        - CodeSampleTests
      gatherCoverageData: true

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.adauto.CodeSampleTests

    dependencies:
      - target: CodeSample