name: CodeSample

options:
  findCarthageFrameworks: true
  # preGenCommand: swiftgen
  # generateEmptyDirectories: true
  # createIntermediateGroups: true

targets:
  CodeSample:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [CodeSample]

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.adauto.CodeSample"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"

    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: XCoordinator
      - carthage: TinyConstraints
      - carthage: AloeStackView

    # preBuildScripts:
    #   - script: swiftgen
    #     name: Swiftgen