name: CodeSample

options:
  findCarthageFrameworks: true
  preGenCommand: swiftgen
  generateEmptyDirectories: true
  createIntermediateGroups: true

projectReferences:
  Core:
    path: Modules/Core/Core.xcodeproj
    embed: true
  
  Components:
    path: Modules/Components/Components.xcodeproj
    embed: true
  

targets:
  CodeSample:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: CodeSample

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.adauto.CodeSample"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: C2BTWK9QR9

      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic

        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.adauto.CodeSample"

    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: XCoordinator
      - carthage: TinyConstraints
      - carthage: AloeStackView
      - target: Core/Core
      - target: Components/Components

    preBuildScripts:
      - script: swiftgen
        name: Swiftgen