name: Core

options:
  generateEmptyDirectories: true
  createIntermediateGroups: true

targets:
  Core:
    type: framework
    platform: iOS
    deploymentTarget: '13.0'
    sources: Core

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.adauto.Core"
      
    dependencies:
      - framework: ../../Carthage/Build/RxSwift.xcframework
      - framework: ../../Carthage/Build/RxCocoa.xcframework
      - framework: ../../Carthage/Build/RxRelay.xcframework